name: Helenedaim
favicon: null
layout_spectrum: 0.25626
typography_spectrum: 0.49332
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010000'
    - '#4a413a'
    - '#8d623f'
    - '#bca38d'
    - '#fef1cc'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
