name: Helenedaim
favicon: null
layout_spectrum: 0.25626
typography_spectrum: 0.49332
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffb'
    - '#010101'
    - '#0083ce'
    - '#81713e'
    - '#98c2d8'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
