name: Helenedaim
favicon: null
layout_spectrum: 0.2617054604925215
typography_spectrum: 0.10822104779072106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001300'
    - '#825734'
    - '#d19165'
    - '#ddd3c9'
    - '#d3b291'
  brandStrength: 0.5
  lightness: 0.40763855911791325
  saturation: 0.9163312762975693
  rhythmicContrast: 0.043641438242048025
purpose: []
