name: Helenedaim
favicon: null
layout_spectrum: 0.99917
typography_spectrum: 0.49332
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6e5a28'
    - '#d7b053'
    - '#8b02d4'
    - '#fef4b9'
    - '#000200'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
