name: Helenedaim
favicon: null
layout_spectrum: 0.99917
typography_spectrum: 0.49332
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#782eb0'
    - '#ffffff'
    - '#aaff00'
    - '#ffaa00'
    - '#8d5440'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
